### ISSUE TITLE
Can't run on Nodejs due to dependency on document

### ISSUE THREAD

**Issue by Ghirigoro** [thoov/mock-socket#10]
the urlTransform function uses the global document variable which doesn't exist in Nodejs.

**Comment by thoov** [comment]
Thanks @Ghirigoro for the feedback. I am currently working on a solution for this #9. I hope to have a solution soon.

**Comment by thoov** [comment]
@Ghirigoro I have updated the url parsing logic and updated the npm & bower packages to v0.1.0 with those changes. Could you try it out on nodejs and see if it fixes your case?

**Comment by Ghirigoro** [comment]
Works great now! Thanks.
