### ISSUE TITLE
bower install mock-socket not working

### ISSUE THREAD

**Issue by rlamorea** [thoov/mock-socket#133]
When I do `bower install --save-dev mock-socket` for version `^6.0.1`
There is no `mock-socket.js` (or `mock-socket.min.js`) file anywhere
in the installed source.

I can see the file in the GitHub repo, but for whatever reason, it does not
show up when installed by bower.

**Comment by thoov** [comment]
Can you try installing now. I updated to 6.0.3 which in mock-socket/dist/mock-socket.js should be the file that you need.

**Comment by rlamorea** [comment]
Yes, using 6.0.3 worked.  Thanks!
