### ISSUE TITLE
js:babel-register doesn't seem to this code. I get an error with default arguments

### ISSUE THREAD

**Issue by funkjunky** [thoov/mock-socket#140]
constructor(url, options = {}) {

Unexpected token =

Even if I use the require method, it's still es6 and still errors.

I'm running mocha via:
mocha --require babel-polyfill --compilers js:babel-register

**Comment by abramz** [comment]
I was able to get 5.0.1 (last version before 6) working w/o a problem

**Comment by thoov** [comment]
Let me take a look into this and see if I can reproduce it.

**Comment by thoov** [comment]
@funkjunky @abramz What version of node are you guys using?

**Comment by abramz** [comment]
I am using `v4.6.2`

**Comment by thoov** [comment]
Found the error. I forgot to publish versions 6.0.2 & 6.0.3 which contained the fix for this issue. I just published version 6.0.3 to npm. Can you install that version and see if it works for you. Thanks!
