### ISSUE TITLE
re-assigning onclose does not get rid of the old event listener

### ISSUE THREAD

**Issue by stevenxxiu** [thoov/mock-socket#143]
re-assigning the following to a `WebSocket` instance does not remove the old event listener, which is not the case for real sockets

      onopen
      onmessage
      onclose
      onerror

Example code would be:

    let ws = new WebSocket('ws://localhost:8080')
    ws.onclose = () => console.log('listener 1')
    ws.onclose = () => console.log('listener 2')

In a browser only listener 2 would be logged.

**Comment by stevenxxiu** [comment]
Here's an (ugly) work-around for now:

    let dispatchEvent = WebSocket.prototype.dispatchEvent
    WebSocket.prototype.addEventListener = function(event, listener){this.listeners[event] = listener}
    WebSocket.prototype.dispatchEvent = function(event, ...customArguments) {
      let res = false
      let listener = this.listeners[event.type]
      if(listener){
        this.listeners[event.type] = [listener]
        res = dispatchEvent.call(this, event, ...customArguments)
        this.listeners[event.type] = listener
      }
      return res
    }

**Comment by roddolf** [comment]
One should also be posible to assign for example `null` to remove the listener.
