### ISSUE TITLE
websocket onmessage fired before onopen

### ISSUE THREAD

**Issue by wangtao0101** [thoov/mock-socket#157]
` mockServer.on('connection', () => {
            mockServer.send('test message');
        });`

**Comment by nicolas-maurice** [comment]
+1

**Comment by thoov** [comment]
@wangtao0101 @nicolas-maurice A fix for this is in version 6.1.0. Could you test out and see if that works for you?

**Comment by nicolas-maurice** [comment]
Everything good for me ! Thanks guys !!
