### ISSUE TITLE
Was there a breaking change in 6.1?

### ISSUE THREAD

**Issue by michielbdejong** [thoov/mock-socket#166]
The unit tests of one of our projects, which depend on mock-socket, spontaneously stopped passing:
```sh
git clone https://github.com/interledgerjs/ilp-plugin-bells
cd ilp-plugin-bells
npm install
npm install mock-socket@6.1
npm run test # will fail
npm install mock-socket@6.0
npm run test # will pass
```

We have [fixed the issue](https://github.com/interledgerjs/ilp-plugin-bells/pull/131/files) for our project, and I don't know what changed between 6.0 and 6.1, but this does suggest that according to semver, 6.1 should have been a major version, not a minor?

Thought I'd give you a heads-up. :)

**Comment by thoov** [comment]
Sorry for the breakage @michielbdejong and thanks for the heads up. The only changes between 6.0.4 and 6.1 are listed here (https://github.com/thoov/mock-socket/releases/tag/6.1.0) but if I had to guess you probably ran against this change (https://github.com/thoov/mock-socket/pull/165) which was fixing this issue (https://github.com/thoov/mock-socket/issues/157). The reason for why I did minor update and not a major two fold: the first was that I was unaware that it would be a breaking change and second the change was for a bug and I wanted to get the bug fix out for more people. If I have time I will check out your repo and see what I can infer from the tests that are breaking.
