### ISSUE TITLE
Not compatible with angular 2+

### ISSUE THREAD

**Issue by georgeedwards** [thoov/mock-socket#169]
I am trying to unit test an angular service in my application, which creates socket.io client. My service looks something like this:

    export class SocketService {
      private name: string;
      private host: string = window.location.protocol + "//" + window.location.hostname + ":3000";
      socket: io.Socket;
    
      constructor() { }
    
      subscribeEvent(name: string): Observable<IJobResp> {
        this.setup(name);
        return new Observable(observer => {
          this.socket.on('job', val => observer.next(val))
        })
      }
   
      private setup(name: string) {
        this.name = name;
        let socketUrl = this.host + "/" + this.name;
        this.socket = io.connect(socketUrl);
      }
    }

So to write my test, I am using the mock-socket library to set up a mock socket.io server. Here is what the test looks like:

    describe('SocketService', () => {
      let socket;
    
      const mockServer = new Server('http://localhost:3000/');
      mockServer.on('connection', server => {
        mockServer.emit('job', 'test message 1');
      });
    
      (window as any).io = SocketIO;
      beforeEach(() => {
        TestBed.configureTestingModule({
          providers: [JobService]
        });
      });

      it('should xyz, inject([JobService], fakeAsync((service: JobService) => {
        service.subscribeEvent('/').subscribe(val => {
          expect(val).toEqual('test message 1');
        })
      })));
    });

However, that test throws the error:

> Error: Cannot make XHRs from within a fake async test.

If I don't have the `fakeAsync`, then the test passes before the assertion in the `subscribe()` is processed.

**Comment by ebaker** [comment]
+1 also running into the same issue

**Comment by georgeedwards** [comment]
Additionally If I try to just use async, I get this:

```
  it('should subscribe to dwnTime events', async(inject([JobService], (service: JobService) => {
    service.subscribeEvent('line/602').subscribe(val => {
      expect(val).toEqual('test 2');
    })
  })));
```
This doesn't seem to work, I get error: `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

**Comment by thoov** [comment]
@ebaker @georgeedwards Thanks for bringing this up. Are either of you able to create a sample repo that I can debug against so I can see what is going on?

**Comment by georgeedwards** [comment]
@thoov Thanks for getting back to us. Please see [this](https://github.com/georgeedwards/mocksocketdemo). I have tried to keep this as close to the docs suggestions. 

1. `yarn install` or ` npm i`
2. `ng test`

**Comment by thoov** [comment]
Thanks @georgeedwards. I will take a look at that shortly and report back with what I find (and hopefully a solution or fix)

**Comment by thoov** [comment]
Ok so I figured out what was going on in the sample repo that you sent me @georgeedwards. The issue is that the window object is not properly being stubbed out. This line (https://github.com/georgeedwards/mocksocketdemo/blob/master/src/app/socket-demo.service.ts#L13) is never being swapped out with the MockSocketIO object. Basically you need to do something like this:

```js
import { Injectable } from '@angular/core';
import * as io from 'socket.io-client';

@Injectable()
export class SocketDemoService {
  socket: io.Socket;
  messages: Array<string>;
  constructor() {
    this.messages = [];
  }

  setup() {
    if (window.SocketIO) {
      this.socket = window.io.connect();
    }
    else {
      this.socket = io.connect('http://localhost:8080');
    }
    this.socket.on('chat-message', data => {
      this.messages.push(data);
    });
  }
}
```

Let me know if you need me to explain if differently

**Comment by georgeedwards** [comment]
@thoov OK, thanks for finding that!
Would be really nice to not have to change the code you are trying to test. Having separate logic specifically for testing always makes me slightly nervous, but it's a good work around 👍

**Comment by thoov** [comment]
@georgeedwards 100% agree. Im going to continue to think about your use case and see if I can come up with a better solution. I will post it here if I do

**Comment by georgeedwards** [comment]
@thoov Awesome, thanks.

One other issue I am facing is how to run multiple tests with different server configurations, I currently have this:

```
  it('should subscribe to job events', async(inject([JobService], (service: JobService) => {
    mockServer = new Server('http://localhost:3000/line/602');
    mockServer.on('connection', server => {
      mockServer.emit('job', 'test message 1');
    });
    (window as any).MockSocketIo = SocketIO;

    service.subscribeEvent('line/602').subscribe(val => {
      expect(val).toEqual('test message 1');
      mockServer.stop();
    })
  })));


  it('should emit jobresp event on comment complete', inject([JobService], (service: JobService) => {
    mockServer = new Server('http://localhost:3000/line/602');
    mockServer.on('jobresp', server => {
      mockServer.emit('job', 'test message 2');
    });

    service.subscribeEvent('line/602').subscribe(val => {
      expect(val).toEqual('test message 3');
    })

    service.completeJob(('job1' as any))
  }));
```

but get error:

> Error: SocketIO is already in CLOSING or CLOSED state

Any idea where this is going wrong?

**Comment by georgeedwards** [comment]
@thoov any idea on how to run multiple consecutive tests with different servers, as shown above?

**Comment by thoov** [comment]
Hi @georgeedwards. Sorry for the delay, I am currently in Europe so don't have a ton of laptop time. There are a few things it might be but first can you verify that `mockServer.stop();` is called in the first test? The second thing is that could you verify that if you comment out the first test the second one passes and if you comment out the second test the first one passes?

**Comment by KevinBeckers** [comment]
Any news?
