### ISSUE TITLE
Could not import on Angular 4/ES6

### ISSUE THREAD

**Issue by millerf** [thoov/mock-socket#172]
When importing your module, I get this error:
TS7016: Could not find a declaration file for module 'mock-socket'.

I have found the solution here:
https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

It seems '.js' needs to be removed from package.json.

Also, I had to use npm to install instead of yarn, but yarn was yielding the same error...

**Comment by thoov** [comment]
@millerf Thanks for finding this out. Will fix shortly

**Comment by millerf** [comment]
Thanks. Do you want me to make a PR?

**Comment by thoov** [comment]
@millerf Yes that would be great!
