### ISSUE TITLE
setTimeout in jest

### ISSUE THREAD

**Issue by jpobley** [thoov/mock-socket#176]
This isn't really an issue with the library as it is a tip about usage, but I wasn't sure where else to put it. This library is awesome :)

## The Setup
* macOSX Sierra 10.12.6
* node v7.10.0
* React app via `create-react-app` (which includes `jest` testing framework)
* jest v21.0.0-beta.1

## The Problem
The mock server wasn't firing the handler registered with `mockServer.on('connection', ...)`, and the WebSocket instance always had a `readyState === 0`. I was using a direct copy and paste of the [example](https://github.com/thoov/mock-socket#native-websocket-example) on the homepage.

## The Process
The mock `WebSocket` uses [`delay()`](https://github.com/thoov/mock-socket/blob/master/src/websocket.js#L104) in its constructor to make sure that `on*` callbacks can be registered before the server starts triggering events.

The [`delay` helper](https://github.com/thoov/mock-socket/blob/master/src/helpers/delay.js) in turn will use a `setTimeout` to call the provided function. After sprinkling `console.log` all over the place, I realized the `setTimeout` in `delay()` was never being fired.

It turns out `jest` just doesn't even acknowledge native timer functions and instead requires you to [mock them](https://facebook.github.io/jest/docs/timer-mocks.html). Today I learned.

## The Solution
1. Call `jest.useFakeTimers();` at the top of the test file.
2. Call `jest.runOnlyPendingTimers();` after attaching handlers to the `WebSocket` instance
```javascript
import { Server } from 'mock-socket';

jest.useFakeTimers();

describe('my ws test', () => {
  it('connects', () => {
    const msgs = [];
    const url = 'ws://localhost:8080';
    const mockServer = new Server(url);
    mockServer.on('connection', server => {
        server.send('you are connected');
    });

    const ws = new WebSocket(url);
    ws.onmessage = (msg) => msgs.push(msg);

    jest.runOnlyPendingTimers();

    expect(msgs.length).toBe(1);
  });
});
```

**Comment by doeg** [comment]
Thank you so much for this example. I found it really helpful. 

I think there's a small typo:

```
    mockServer.on('connection', server => {
        // The example above has `mockServer.send`, 
        // however it's `server` (the socket) that has the `.send` function. 
        server.send('you are connected');
    });
```

**Comment by jpobley** [comment]
Oh, good catch! I also found another typo as I read through it.

**Comment by iot-resister** [comment]
@jpobley  I copied and pasted the answer and `onmessage` never runs... so I'm getting
```
    Expected: 1
    Received: 0
```

I'm running this using reacts testing library
```json
    "@testing-library/jest-dom": "^5.11.4",
    "mock-socket": "^9.0.7",
```
