### ISSUE TITLE
no type delcaration file

### ISSUE THREAD

**Issue by Parcley** [thoov/mock-socket#177]
when importing mock-socket into a typescript application, which has noImplicitAny checks turned on, the compile will fail: 

tested with mock-socket@7.0.0 and typescript@2.5.2:
```
error TS7016: Could not find a declaration file for module 'mock-socket'. 
'<my-app>/node_modules/mock-socket/dist/mock-socket.js' implicitly has an 'any' type.
```

maybe we could use https://github.com/tbekolay/types-mock-socket as a first draft for a .d.ts file of mock-socket?

**Comment by dinfer** [comment]
How it's going?

**Comment by thoov** [comment]
I have added a first pass of a definition file (https://github.com/thoov/mock-socket/commit/d5d4eeb54c0a9af2031d74e3bbb9113bb46bb23f). I don't use typescript for my project so if you run into any inconsistencies please open an issue.
