### ISSUE TITLE
Ionic 3: No provider for String!

### ISSUE THREAD

**Issue by ws-hofshteyn** [thoov/mock-socket#180]
Hi there! Trying use ` mock-socket ` in my Ionic 3 app. But after installing (via npm) and importing it into the spec file I have following error in terminal: 

`  Failed: No provider for String!
    _throwOrNull@webpack:///~/@angular/core/@angular/core.es5.js:2772:0 <- src/test.ts:3052:45
    _getByKeyDefault@webpack:///~/@angular/core/@angular/core.es5.js:2811:0 <- src/test.ts:3091:37
    _getByKey@webpack:///~/@angular/core/@angular/core.es5.js:2743:0 <- src/test.ts:3023:41
    get@webpack:///~/@angular/core/@angular/core.es5.js:2612:0 <- src/test.ts:2892:30
    get
    getInternal
    get@webpack:///~/@angular/core/@angular/core.es5.js:3576:25 <- src/test.ts:3856:55
    get@webpack:///~/@angular/core/@angular/core/testing.es5.js:760:0 <- src/test.ts:19722:50
    webpack:///src/services/server-communication.service.spec.ts:16:34 <- src/test.ts:129524:34
    invoke@webpack:///~/zone.js/dist/zone.js:365:0 <- src/test.ts:123435:31
    onInvoke@webpack:///~/zone.js/dist/async-test.js:49:0 <- src/test.ts:122260:45
    onInvoke@webpack:///~/zone.js/dist/proxy.js:76:0 <- src/test.ts:122963:47
    invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- src/test.ts:123434:40
    runGuarded@webpack:///~/zone.js/dist/zone.js:138:0 <- src/test.ts:123208:53
    runInTestZone@webpack:///~/@angular/core/@angular/core/testing.es5.js:110:0 <- src/test.ts:19072:35
    webpack:///~/@angular/core/@angular/core/testing.es5.js:49:0 <- src/test.ts:19011:26
    invoke@webpack:///~/zone.js/dist/zone.js:365:0 <- src/test.ts:123435:31
    onInvoke@webpack:///~/zone.js/dist/proxy.js:79:0 <- src/test.ts:122966:45
    invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- src/test.ts:123434:40
    run@webpack:///~/zone.js/dist/zone.js:125:0 <- src/test.ts:123195:49
    webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:122663:37
    execute@webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- src/test.ts:122693:46
    execute@webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- src/test.ts:122693:46
    webpack:///~/zone.js/dist/jasmine-patch.js:129:91 <- src/test.ts:122690:134
    invokeTask@webpack:///~/zone.js/dist/zone.js:398:0 <- src/test.ts:123468:36
    runTask@webpack:///~/zone.js/dist/zone.js:165:0 <- src/test.ts:123235:57
    drainMicroTaskQueue@webpack:///~/zone.js/dist/zone.js:591:0 <- src/test.ts:123661:42
    run@webpack:///~/core-js/modules/es6.promise.js:72:0 <- src/test.ts:131479:29
    webpack:///~/core-js/modules/es6.promise.js:85:0 <- src/test.ts:131492:33
    flush@webpack:///~/core-js/modules/_microtask.js:18:0 <- src/test.ts:129908:11
`

Ionic info: 

` cli packages: (/Users/admin/Documents/Work/ionicapp/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

    global packages:

    Cordova CLI : 7.0.1 

    local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.0.1

    System:

    Node : v8.2.1
    npm  : 5.4.2 
    OS   : macOS Sierra`

**Comment by ws-hofshteyn** [comment]
Problem was in my app, not in package.

**Comment by thoov** [comment]
@ws-hofshteyn Glad you found the root cause. Let me know if you run into anything else
