### ISSUE TITLE
MockServer events

### ISSUE THREAD

**Issue by Ghirigoro** [thoov/mock-socket#19]
It looks like MockServer is intended to emulate the WebSocketServer from ws. One difference though is that ws passes in strings rather than objects on socket events. For example:

socket_server.on('connection', function(socket) {
	socket.on('message', function (message) {
		// using ws message is a string containing the event data
                // using MockServer message is an event object
	});
}

If the intent is to make MockServer play nice with ws, matching ws's behavior would be a welcome change.

**Comment by thoov** [comment]
@Ghirigoro Great catch and yes I would like MockServer to match WS's behavior. I will send an update fixing this.
