### ISSUE TITLE
Support for Phoenix Socket?

### ISSUE THREAD

**Issue by PabloReszczynski** [thoov/mock-socket#207]
Is there a way to use this library to mock a Phoenix server?

**Comment by PabloReszczynski** [comment]
Had some time investigating and it's really complex to simulate distincts channels, the reply system and the error system.

**Comment by thoov** [comment]
@KHMtravel I don't have any experience with Phoenix so I cant offer much help. I know they are using mock-socket for their tests which you might be able to get some insights from by looking at those (https://github.com/phoenixframework/phoenix/blob/2bfc3ed17f0c1c7e9a23d97ffaf366ec5d935d25/assets/test/socket_test.js). I am open to any PRs that would be make supporting phoenix possible/easier. I am going to close this issue but feel free to add info here if you find anything.
