### ISSUE TITLE
All sockets receive the sent message

### ISSUE THREAD

**Issue by ghost** [thoov/mock-socket#209]
I cannot send a message to a single web socket by id. Emit(...) sends the message to all connected web sockets (broadcast).

**Comment by pronebird** [comment]
Same issue here. 

1. `send` simply emits a message to everyone, useless if I have to test multiple clients.

2. `server.on` does not filter by clients either so it's pointless at best or requires a lot of noise in code in order to make it work.

**Comment by thoov** [comment]
This has now been fixed and will be included in the 8.x series that will be released shortly
