### ISSUE TITLE
Wrong TypeScript definition for .on() method

### ISSUE THREAD

**Issue by tijp** [thoov/mock-socket#221]
Hi,

When using the example from the docs, I get the following TypeScript error:

<img width="752" alt="screen shot 2018-07-11 at 16 27 41" src="https://user-images.githubusercontent.com/9055401/42578863-648bbf96-8527-11e8-9014-6a768473c977.png">

This is because the `.on` method uses VoidFunction in its TypeScript definition, which implies that there are no parameters (but there is, the socket parameter!).

Changing the definition from this:

https://github.com/thoov/mock-socket/blob/e80dea254bcda8ba1479d6a48c29f2f4688d7445/index.d.ts#L41

to this fixes it:
`on(type: string, callback: (socket: WebSocket) => void): void;`

I can make a PR for this, however I don't know if this breaks things for others.

**Comment by haplesshero13** [comment]
Same problem here. This is preventing us from using mock-socket in TypeScript. We either have to override the typings ourselves, or create a .js test instead. Neither of those seems like a great option.

**Comment by tijp** [comment]
Thanks for the quick fix!
