### ISSUE TITLE
A few types can't be found

### ISSUE THREAD

**Issue by AmirF27** [thoov/mock-socket#226]
I'm getting an error on the `EventHandlerNonNull` and `BinaryType` types.

```
ERROR in node_modules/mock-socket/index.d.ts(21,13): error TS2304: Cannot find name 'EventHandlerNonNull'.
node_modules/mock-socket/index.d.ts(22,14): error TS2304: Cannot find name 'EventHandlerNonNull'.
node_modules/mock-socket/index.d.ts(23,14): error TS2304: Cannot find name 'EventHandlerNonNull'.
node_modules/mock-socket/index.d.ts(28,16): error TS2304: Cannot find name 'EventHandlerNonNull'.
node_modules/mock-socket/index.d.ts(29,17): error TS2304: Cannot find name 'BinaryType'.
```

I already have the `dom` library defined in my `tsconfig.json` file, and this is where those types seem to be be.

I'm using version 8.0.2.

How can this be resolved? I have tried many things, to no avail.

**Comment by daveschwerstein** [comment]
I am having the same issue.

**Comment by guilhermechiara** [comment]
Same problem here. Trying to figure out what's exactly happening.

**Comment by benplummer** [comment]
Anyone found a solution or work-around to this?

**Comment by odyzxc** [comment]
Same issue here.

**Comment by Townsheriff** [comment]
Missing typings are added in Typescript 2.8. Update typescript in project or add missing typings from https://github.com/Microsoft/TypeScript/blob/release-2.9/lib/lib.dom.d.ts

**Comment by orgads** [comment]
I'm using Typescript 4.4.3, and still has the same issue.

**Comment by andreyfel** [comment]
Hi @thoov! Could you please cut a new release with this fix?
