### ISSUE TITLE
Event handler getters should return a single function

### ISSUE THREAD

**Issue by juangl** [thoov/mock-socket#242]
Right now, event handler's (like `onopen`, and `onerror`) getters should return a single function instead of the present behavior where they return an array. I haven't gone through the spec but that's what the browser does. If that sounds correct I'm happy to send a PR.

**Comment by ritave** [comment]
I confirm that this is expected behaviour which the Mock WebSocket wrongly implements

**Comment by Atrue** [comment]
If you have time you can create a PR for this
