### ISSUE TITLE
WebSocket connected with query params won't send a message

### ISSUE THREAD

**Issue by pablobirukov** [thoov/mock-socket#274]
With https://github.com/thoov/mock-socket/pull/271, `"message"` handler is never triggered if a WS had query params

```js
  const testServer = new Server('ws://localhost:8080');

  testServer.on('connection', socket => {
    socket.on('message', data => {
      // never called
    });
  });

  const mockSocket = new WebSocket('ws://localhost:8080?foo=bar');

  mockSocket.onopen = function open() {
    this.send('Testing');
  };
```

That's because in WS' `send` handler lookup performed for the full URL, that includes query part `const server = networkBridge.serverLookup(this.url);`

**Comment by sechel** [comment]
Hey @pablobirukov, thank you for your report. Your code looks ok. #271 was about making this very use case possible, so I will check.

**Comment by sechel** [comment]
Hey, @pablobirukov you are right. I think your #275 will do the trick. Thanks for checking. Unfortunately I cannot merge it myself, we will need to wait for @thoov to accept.

**Comment by pablobirukov** [comment]
Any progress @thoov?

**Comment by Zarathustra2** [comment]
Would be nice if #275  gets merged. I ran into the same issue.

**Comment by timshannon** [comment]
Is anyone else still having issues with this?  I've installed version 9.0.2, and I still can't mock websockets defined with query parms.

**Comment by pablobirukov** [comment]
@timshannon it hasn't been released

**Comment by thoov** [comment]
Can you try 9.0.3. I just released it

**Comment by timshannon** [comment]
Still not working for me unless, I remove my query parms.

**Comment by timshannon** [comment]
Works fine if I literally copy and paste the `trimQueryPartFromURL` func into my test and run it before I pass my URL into mock-socket.

**Comment by timshannon** [comment]
I'm using `new Server` btw.  Maybe that wasn't covered by the PR.

```typescript
import { Server } from "mock-socket";
...
const server = new Server(trimQueryPartFromURL(socket.socketAddress)); 
```

**Comment by timshannon** [comment]
Yeah I think *maybe* [attachServer](https://github.com/thoov/mock-socket/blob/master/src/network-bridge.js#L57) needs to also `trimQueryPartFromURL`?

**Comment by timshannon** [comment]
Should I open a new issue?  This still doesn't seem to be fixed for me.

**Comment by marcelotedeschi** [comment]
I can also confirm `9.0.3` is still not working when having query params on the url for `new Server`. When manually removing these, clients _with_ QPs are actually able to connect!

**Comment by VTarasich** [comment]
Prepared a PR with the fix that worked for me

https://github.com/thoov/mock-socket/pull/343
