### ISSUE TITLE
Mocking 'ws' WebSocket, missing EventEmitter methods

### ISSUE THREAD

**Issue by DBosley** [thoov/mock-socket#292]
When using `mock-socket` to mock the WebSocket type from the `ws` module, there are missing methods. The WebSocket type from `ws` extends EventEmitter while the `mock-socket` implementation does not. The method that my project needs that's missing is `once()`. I'm not sure which other EventEmitter methods are missing, but I assume there are a few.

**Comment by davydof** [comment]
any updates? :)

**Comment by Atrue** [comment]
The mock-socket is intended to mock the browser WebSocket instance. The `ws` package is used on the node js only and does not work in the browser at all https://github.com/websockets/ws?tab=readme-ov-file#ws-a-nodejs-websocket-library.

So if you are writing a js code to be run on the browser, you use the native WebSocket instance or any wrapper for it. So here you can use `mock-socket` to imitate client(browser)-server behaviour.

If you are writing a js code to be run on the NodeJS, you can choose `ws` package, but you can't use `mock-socket` to test it. I suppose you can use something like node proxy to test it https://github.com/websockets/ws?tab=readme-ov-file#how-to-connect-via-a-proxy, but it’s better to check the docs api.
