### ISSUE TITLE
Don't stub out WebSocket by default

### ISSUE THREAD

**Issue by megancooper** [thoov/mock-socket#308]
Would it be possible to not stub out the native `WebSocket` by default? I am creating an application where I want to use both mock and real sockets. Is there a current work-around for this?

**Comment by shibbas** [comment]
I'm interested in this as well. Any suggestions?

**Comment by Atrue** [comment]
Fixed in 9.1.0
Example: `new Server('ws://localhost:8080', { mock: false });`
