### ISSUE TITLE
Authorization Bypass Through User-Controlled Key in NPM url-parse prior to 1.5.8.

### ISSUE THREAD

**Issue by ahtokca** [thoov/mock-socket#358]
Hi Thoov,

Would it be possible to upgrade to a version of url-parse which is not vulnerable (https://github.com/advisories/GHSA-rqff-837h-mm52)?
According to https://github.com/thoov/mock-socket/blob/master/yarn.lock url-parse@^1.5.2: is used by mock-socket.

thank you in advance

**Comment by Atrue** [comment]
Upgraded in 9.1.3
