### ISSUE TITLE
[Typescript] Client.addEventListener and Server.addEventlistener has wrong typing

### ISSUE THREAD

**Issue by Lukas-Kullmann** [thoov/mock-socket#371]
Unfortunately, the typings of `Client.addEventListener` and `Server.addEventListener` are not ideal. Both `Client` and `Server` implement the custom `EventTarget` interface which defines the parameter of the listener as `Event`. That is not correct, however.
Most event listeners will never get an actual `Event`, but rather a custom property that depends on the event itself (e.g. the `connection` event on the `Server` will get a `Client`, not `Event`).

So if you do the following, you will get an error:

```ts
import { Client, Server } from 'mock-socket';

const server = new Server('wss://example.com');

// this does not work ❌
server.addEventListener('connection', (client: Client) => {
  // ...
});
```

You will get the following error:

```
TS2345: Argument of type '(client: Client) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject | null'.
Type '(client: Client) => void' is not assignable to type 'EventListener'.
Types of parameters 'client' and 'evt' are incompatible.
Type 'Event' is missing the following properties from type 'Client': close, on, url, CONNECTING, and 17 more.
```

If you use `Client.on` or `Server.on`, it works the way it should, however.

```ts
// everything is fine ✅
server.on('connection', (client: Client) => {
  // ...
});
```

My problem here is, that there is no `off` on `Server` and `Client` that allows me to remove the event listener again. So I have to resort to `.removeEventListener`. It works fine. However, the typings are wrong here, too.

So I would suggest to add a `.off` functionality or add overloads for `.addEventLister` and `.removeEventListener` that allows the correct event handlers to be passed. 🙂

**Comment by Atrue** [comment]
Thanks. Fixed in `9.2.0`
