### ISSUE TITLE
send should throw an error if readyState is CONNECTING

### ISSUE THREAD

**Issue by bchirlsbiodigital** [thoov/mock-socket#377]
`.send()` should [throw an error](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send#exceptions) if `readyState` is `CONNECTING`, but this implementation does not. The function [only throws an error](https://github.com/thoov/mock-socket/blob/master/src/websocket.js#L142-L144) if the `readyState` is `CLOSING` or `CLOSED`.

Thanks!

**Comment by Atrue** [comment]
@bchirlsbiodigital Feel free to open a PR with appropriate changes if you have time. Thanks
