### ISSUE TITLE
Export `CloseEvent`

### ISSUE THREAD

**Issue by regseb** [thoov/mock-socket#380]
The [WebSockets specification](https://websockets.spec.whatwg.org/#the-closeevent-interface) defines two classes: `WebSocket` and `CloseEvent`. These two classes don't exist in Node.
Mock Socket already exports `WebSocket`. [**`CloseEvent`**](https://github.com/thoov/mock-socket/blob/57e4b8d/src/event/close.js#L4) should also be exported to use it as polyfill in Node.

```JavaScript
import { WebSocket, CloseEvent, Server } from 'mock-socket';

const server = new Server('ws://localhost:8080', { mock: false });

globalThis.WebSocket = WebSocket;
globalThis.CloseEvent = CloseEvent;
```

**Comment by Atrue** [comment]
This package is not a polyfill, it's a mocking library for the WebSocket. If you have any issues running tests you can open a new PR with the details
