### ISSUE TITLE
Spec doesn't actually say that `send()` should throw when the socket is `CLOSING` or `CLOSED`

### ISSUE THREAD

**Issue by steveluscher** [thoov/mock-socket#381]
This is actually somewhat controversial:

https://github.com/thoov/mock-socket/blob/eab4bf59ab83298ee42a21fc535a369432fe22c6/src/websocket.js#L141-L144

The long discussion at https://github.com/websockets/ws/issues/1515 convinced me that `mock-socket` _shouldn't_ throw an exception here. Browsers don't actually throw when the socket is `CLOSING` or `CLOSED`; they simply print a red console message.

Try:

```ts
const socket = new WebSocket('wss://api.devnet.solana.com');
socket.close(1000);
try {
  socket.send({jsonrpc: '2.0', id: 1, method: 'ping'});
} catch (e) {
  // Despite the fact that the console shows red messages...
  console.error('this never gets hit', e);
}
```

**Comment by steveluscher** [comment]
Related, which is actually the opposite problem: #377.

**Comment by Atrue** [comment]
Release `9.3.0`.  Thanks @steveluscher
