### ISSUE TITLE
The socket-server stops after 1 message is emitted

### ISSUE THREAD

**Issue by JJ** [thoov/mock-socket#387]
[This is not getting a lot of attention in StackOverflow](https://stackoverflow.com/questions/77314546/creating-a-non-stop-websocket-mock-server-in-javascript), so I might as well link it here. Help will be appreciated here or in StackOverflow

**Comment by Atrue** [comment]
I suppose you need to figure out how to work with your test framework. Your tests are not defined properly. I hope it can help you https://mochajs.org/#asynchronous-code

If you think there is an issue in the mock-socket library please create a minimal code snippet. Please also attach the output with the current and expected behaviour. Ideally, this snippet should not have any external library.

**Comment by JJ** [comment]
Thanks for the suggestion. Here's the minimal example without any test code (which was minimal anyway)

```javascript
import { readFileSync } from "fs";
import { WebSocket, Server } from "mock-socket";
import { AIS_API_URL } from "../lib/test-mock.js";

const server = new Server(AIS_API_URL);

let count = 0;
function callback(message) {
  count++;
  if (count === 5) {
    socket.close();
  }
  console.log(message, count);
}

const messageExamples = JSON.parse(readFileSync("message_examples.json"));

server.on("connection", (socket) => {
  const messageType = Object.keys(messageExamples);
  const message =
    messageExamples[messageType[(messageType.length * Math.random()) << 0]];
  socket.send(JSON.stringify(message));
});

const socket = new WebSocket(AIS_API_URL);

socket.addEventListener("error", (event) => {
  console.error(event);
});
socket.addEventListener("message", (event) => {
  const aisMessage = JSON.parse(event.data);
  callback(aisMessage);
});
socket.addEventListener("close", () => {
 console.log("Closing with ", count, " calls" );
});
```

Read file is [this one](https://github.com/JJ/AISstreamer/blob/main/tests/message_examples.json), could be any as long as it's an object.  This prints

```JSON
{
  Message: {
    AddressedBinaryMessage: {
      ApplicationID: [Object],
      BinaryData: '\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x01\x00\x01\x01\x01\x01\x01\x01\x00\x01\x00\x01\x01\x01\x01\x00\x00\x01\x00\x01\x00\x01\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x01\x00\x01\x01\x00\x00\x00\x01\x01\x01\x01\x01',
      DestinationID: 2242174,
      MessageID: 6,
      RepeatIndicator: 1,
      Retransmission: true,
      Sequenceinteger: 0,
      Spare: false,
      UserID: 2242174,
      Valid: true
    }
  },
  MessageType: 'AddressedBinaryMessage',
  MetaData: {
    MMSI: 2242174,
    MMSI_String: 2242174,
    ShipName: '',
    latitude: 36.714150000000004,
    longitude: -4.414563333333334,
    time_utc: '2023-10-15 09:51:08.344744901 +0000 UTC'
  }
} 1
```

(That's essentially one of the stored messages, could have been any other) And exits, having been called a single time as the title of the post says. Is there anything I'm missing here? How could I get the server to run continuously?

**Comment by JJ** [comment]
Just left here for reference. You need to send via the socket everything you want to emit as soon as the connection is made:

```javascript
server.on("connection", (socket) => {
  console.log("connected " + socket.url);
  for (const message of Object.keys(messageExamples)) {
    socket.send(JSON.stringify(messageExamples[message]));
  }
});
```

**Comment by Atrue** [comment]
So what's the issue? You can send as many messages as you want
https://github.com/thoov/mock-socket#server-methods
Your example send the only message once the socket is connected and everything is handled properly
