### ISSUE TITLE
Question about using MockServer

### ISSUE THREAD

**Issue by ashchurova** [thoov/mock-socket#58]
Hi, I am trying to use your library to mock web socket server in my unit tests. I run my tests in Chrome. Unfortunately "mocking" does not happen for me. I do create the instance of MockServer with correct url but when the code I test tries to open WebSocket I get an exception "WebSocket connection to 'ws://127.0.0.1:8585/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED". I think I do everything correctly. I was hoping you could point me in the right direction. Thank you, Anna

**Comment by dustinfarris** [comment]
what was the solution to this?

**Comment by taylorjdawson** [comment]
Getting the same error.
