### ISSUE TITLE
Unit tests breaking in Firefox

### ISSUE THREAD

**Issue by nomve** [thoov/mock-socket#61]
Hi,

my unit tests are breaking in Firefox every time there is something depending on a a message being received from the MockServer. I thought I messed something up in my code, but after checking in more detail, realized out even your unit tests break in firefox, e.g.

```
Unit - EventTarget: adding/removing "message" event listeners works (1, 0, 1)Rerun1 ms

    Expected 3 assertions, but 0 were run
```

I've figured out it's because in `createMessageEvent` the `messageEvent.type` property gets lost and then no listeners are found in `dispatchEvent`. So adding it back like you did with `.data` and `.origin` helps, but some other tests still break. In general, the tests behave very strange, I have to shutdown Firefox completely because after the first time, all the tests break on refresh.

**Comment by adirhaleli** [comment]
I'm having failing tests in Firefox too

**Comment by thoov** [comment]
thanks for finding this. I will investigate

**Comment by nomve** [comment]
Thanks :+1:
