### ISSUE TITLE
Run mock-socket with jsdom

### ISSUE THREAD

**Issue by mnibecker** [thoov/mock-socket#71]
I ran into a pretty odd issue using this (great) library in conjunction with jsdom. When you use jsdom you override `global.window` with a window obj provided by jsdom. This is causing issues with mock-socket because it looks for the `Event` class in window, and jsdom provides a partially implemented version of `Event` that does implement the same signature that we find in the standard browser event. Thus, the passed `type` and `config` params get ignored and we have an event with no type that cannot be routed to a listener. We don't have this problem with Other Event Types (e.g. CloseEvent) because mock-socket doesn't find them in jsdom's provided window obj and library defaults to `NodeEvent`.

#### Proposed Solution

I think we should change the way the library determines if we're running in node or not. Currently if the `window` object is defined that the globalContext is set to window. Obviously for those using jsdom (or I imagine any other node library that spoofs the browser) things fall apart. The answer in this SO thread (http://stackoverflow.com/questions/17575790/environment-detection-node-js-or-browser) recommends using something akin to `this === window` to determine such cases. I think this is an elegant solution. If you're running jsdom, it should say we're using Node.

If the maintainers think this is a good approach, I'll gladly throw up a pr for this.

**Comment by thoov** [comment]
@mnibecker Thanks for finding this! What version of mock-sockets are you currently using?

**Comment by mnibecker** [comment]
I'm using version 1.0.6

**Comment by thoov** [comment]
@mnibecker Can you try with 2.0.0? I changed the eventing system and that might solve your problem.

**Comment by mnibecker** [comment]
cool, I'll try it out shortly and post my results here.

**Comment by mnibecker** [comment]
Nice this seems to work with 2.0.0! Closing issue...

**Comment by thoov** [comment]
@mnibecker thanks for checking!

**Comment by nilsi** [comment]
Hi, 

I still have a problem with running this in conjunction with jsdom. I need jsdom to access `window.location.protocol` and `window.location.host` to construct WebSocket URL but if I add it I'm getting `ReferenceError: WebSocket is not defined` and if I remove jsdom I'm getting `ReferenceError: WebSocket is not defined`. Not sure how to proceed.

**Comment by thoov** [comment]
@nilsi I will take a look into this. Do you have an example that shows it not working that you could paste here?

**Comment by thoov** [comment]
@nilsi I added an example that works in JSDOM here (https://github.com/thoov/mock-socket/pull/191/files). If you are still running into issues could you open another issue
