### ISSUE TITLE
Ember test support.

### ISSUE THREAD

**Issue by yratanov** [thoov/mock-socket#8]
Hi, thank you for the lib.
I tried to use it in my Ember qunit acceptance tests and faced error with Ember run loop.
You can't use ```setTimout``` in ember tests without wrapping it with promise object or using ```Ember.run.later```.

I understand the lib is supposed to be used not only in Ember environment, but can we include RSVP promises and wrap delay code with it or should I just fork it?

**Comment by thoov** [comment]
@yratanov I am using this in [ember-websockets](https://github.com/thoov/ember-websockets) and not running into this issue. If you are able to come up with a fix submit a PR and I will happily merge it in or if you could give me more info / a jsbin to look at I can try to come up with a fix.

**Comment by yratanov** [comment]
@thoov add some async logic in your callbacks (e.g. ```onmessage```), for example push in the store.

**Comment by thoov** [comment]
@yratanov Are you working on a fork or should work on adding RSVP?

**Comment by yratanov** [comment]
@thoov I can do it. You don't mind if I add RSVP lib?
