### ISSUE TITLE
Emit function parameters (Client and Server) do not mirror Socket.io API

### ISSUE THREAD

**Issue by rocketedaway** [thoov/mock-socket#81]
Hi @thoov,

I have been using your library at work for unit testing a Socket.io based application we are making. I have contributed to the library in [Issue #79](https://github.com/thoov/mock-socket/pull/79) in order to add some missing functionality we needed in our app. 

When running tests I am running into an issue were the API for mock-socket's emit function is not aligned with Socket.io's emit function.

The Socket.io API for emit is `emit(event, ...data)`, which allows for variable amounts of data args to be passed to the callback function listening to the specified event name. 

The mock-socket API for emit is `emit(event, data, options)` for the [server](https://github.com/thoov/mock-socket/blob/master/src/server.js) and `emit(event, data)` for the [client](https://github.com/thoov/mock-socket/blob/master/src/socket-io.js). The mock-socket API does not allow for variable amounts of data args to be passed. We could pass all of our data as an object, but I feel this incorrect.

I looked into making the changes necessary to correct this but it would be a major change to libraries API. I would be willing to do the work to make the modifications to align the API between the two libraries. Before doing this work I wanted first to talk to you about why the API was structured this way and your ideas on how to correct it.

Thanks!

**Comment by thoov** [comment]
@rocketedaway Sorry for the delay in getting back to you. Thanks for finding this. I will update emit to support multiple data args. I should have this done over this weekend.

**Comment by rocketedaway** [comment]
Thanks @thoov. I appreciate the quick turnaround!

**Comment by thoov** [comment]
@rocketedaway I was playing around with an example and didn't see the behavior that you are describing. Main that [emit](https://github.com/socketio/socket.io/#socketemitnamestring-socket) was not respecting additional parameters like:
```
socket.emit('foo', 'bar');
```

Could you create a simple example that shows what you are explaining?

**Comment by rocketedaway** [comment]
@thoov I will do this later this week. Should I just post it in here?

**Comment by rocketedaway** [comment]
```
var MockSocket = require('mock-socket');

var serverUrl = 'http://test';
var server = new MockSocket.Server(serverUrl);

server.on('connection', function (server, socket) {
    server.emit('someServerEvent', 1, 2, 3);
    socket.emit('someSocketEvent', 4, 5, 6);
}); 

server.on('someSocketEvent', function () {
    console.log('someSocketEvent', arguments, arguments.length);
});

var client = new MockSocket.SocketIO(serverUrl);
client.on('someServerEvent', function () {
    console.log('someServerEvent' , arguments, arguments.length);
});

// Prints
// someServerEvent { '0': 1 } 1
// someSocketEvent { '0': 4 } 1
```

**Comment by thoov** [comment]
Ok let me test against this example

**Comment by rocketedaway** [comment]
Hey @thoov any luck reproducing the issue?

**Comment by thoov** [comment]
@rocketedaway Sorry for the delay. I just got married so its been crazy the last couple of weeks with that. 

I ran the example code that you provided and was able to see the same results as you pointed out. However, I created this example:

**index.html**
```html
<html>
<script src="http://localhost:8080/socket.io/socket.io.js"></script>
<script>
  var socket = io('http://localhost:8080');

  socket.on('connect', function () {
    socket.emit('clientEmit', 'foo', 'bar', 'baz');
  });

  socket.on('serverEmit', function (data) {
    console.log(data);
  });
</script>
</html>
```

**server.js**
```js
var app = require('http').createServer(handler)
var io = require('socket.io')(app);
var fs = require('fs');

app.listen(8080);

function handler (req, res) {
  fs.readFile(__dirname + '/index.html',
  function (err, data) {
    if (err) {
      res.writeHead(500);
      return res.end('Error loading index.html');
    }

    res.writeHead(200);
    res.end(data);
  });
}

io.on('connection', function (socket) {
  socket.emit('serverEmit', 'foo', 'bar', 'baz');

  socket.on('clientEmit', function (data) {
    console.log(data);
  });
});
```

On both the server and client I just see 'foo' which it appears socket.io is just taking the first argument. This is what mock-socket is currently doing. Do you have an example using pure socket.io where this happens? (I tested against the latest 1.4.5)

**Comment by rocketedaway** [comment]
@thoov Congrats on getting married!! It's a crazy and fun day :)

Okay based on your example you are only printing the first argument. To access all the data being returned by the emit callback in your example you would have to do the following:

```
socket.on('clientEmit', function (dataFoo, dataBar, dataBaz) {
    console.log(dataFoo, dataBar, dataBaz); // OR console.log(arguments)
});
```

Following are code examples to see this in action:

**client.js**
```
const io = require('socket.io-client');

const client = io.connect('http://localhost:8080');
client.on('connect', function () {
    console.log('Conected to IO server: localhost:8080');
    client.emit('clientEmit', 'foo', 'bar', 'baz');
});

```

**server.js**
```
const express = require('express');

const app = express();
const server = require('http').Server(app);
const io = require('socket.io')(server);

server.listen(8080, function () {
    console.log('Server listening on localhost:8080');
});

io.on('connect', function (socket)  {
    socket.on('clientEmit', function () {
        console.log('Socket Event: clientEmit', arguments);
    });
});
```

The above console logs the following from the server
```
Server listening on localhost:8080
Socket Event: clientEmit { '0': 'foo', '1': 'bar', '2': 'baz' }
```

Thanks!
Let me know if you need anything else from me!

**Comment by thoov** [comment]
@rocketedaway Thank you!! Now I see what you are saying (and able to reproduce it). I just updated master with some changes that should support this. Can you install:

```
npm install thoov/mock-socket#master
``` 

And see if this works for you?

**Comment by rocketedaway** [comment]
@thoov Thanks! I will do this today and get back to you.

**Comment by rocketedaway** [comment]
@thoov Looks good! I tested it with our unit tests and it works as expected.

Thanks!

**Comment by thoov** [comment]
Awesome. I just published v4.0.0 which has the change. Thanks for working through this with me!

**Comment by rocketedaway** [comment]
Hi @thoov,

The `dist` files in the package downloaded from `npm` and the github repo are not compiled against the new source. When I tested it before the version was updated I built it locally first.

Sorry!

**Comment by thoov** [comment]
@rocketedaway Oops. I just added them to 4.0.1. Try that version

**Comment by rocketedaway** [comment]
@thoov It's working now. Thanks for the quick turnaround, I really appreciate it! Have a good one.
